AppTestTrastornos/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),
] 

libreria/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('depresion/', views.tests, {'test_nombre': 'PHQ-9'}, name='depresion'),
    path('mdq/', views.tests, {'test_nombre': 'MDQ'}, name='mdq'),
    path('alcoholismo/', views.tests, {'test_nombre': 'AUDIT'}, name='alcoholismo'),
    path('dep-ado/', views.tests, {'test_nombre': 'DEP-ADO'}, name='drogas'),
    path('beck/', views.tests, {'test_nombre': 'BHS'}, name='beck'),
    path('edds/', views.tests, {'test_nombre': 'EDDS'}, name='edds'),
    path('ansiedad/', views.tests, {'test_nombre': 'Ansiedad'}, name='ansiedad'),
    path('estres/', views.tests, {'test_nombre': 'Estres'}, name='estres'),
    path('afectacion-academica/', views.tests, {'test_nombre': 'AfeccionAcademica'}, name='afecciónAcadémica'),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('salir/', views.salir, name='salir'),
    path('registro/', views.registro, name='registro'),
]

libreria/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    correo = models.CharField(max_length=100)
    carrera = models.CharField(max_length=100)
    instituto = models.CharField(max_length=100)
    edad = models.CharField(max_length=100)
    sexo = models.IntegerField()
    semestre = models.CharField(max_length=100)

    # Agrega cualquier otro campo adicional que desees

    def __str__(self):
        return self.user.username


class Test(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    fecha_creacion = models.DateField(auto_now_add=True)
    ultima_actualizacion = models.DateField(auto_now=True)


class Pregunta(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    pregunta = models.TextField()
    tipo_pregunta = models.CharField(max_length=50)
    categoria = models.CharField(max_length=50)
    fecha_creacion = models.DateField(auto_now_add=True)
    ultima_actualizacion = models.DateField(auto_now=True)


class OpcionRespuesta(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion = models.CharField(max_length=255)
    valor = models.IntegerField()


class Respuesta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_respuesta = models.ForeignKey(
        OpcionRespuesta, on_delete=models.CASCADE)


class Instituto(models.Model):
    nombre = models.CharField(max_length=100)


class Carrera(models.Model):
    nombre = models.CharField(max_length=100)


class Calificacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    calificacion = models.IntegerField()

libreria/forms.py
from django import forms
from .models import Usuario


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('correo', 'carrera', 'edad', 'instituto', 'sexo', 'semestre')

libreria/views.py
from django.shortcuts import render, redirect
from .models import Pregunta, Test, Instituto, Carrera, OpcionRespuesta, Respuesta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .forms import UsuarioForm
from django.contrib.auth import logout, login
import random
# Create your views here.

COLORES = ['#9AFAC2', '#FAF499', '#FA8E7D',
           '#FAA8EF', '#CCD3FA', '#C3F9F9', '#9FFA9B']


@login_required
def inicio(request):
    return render(request, 'index.html')


def registro(request):
    carreras = Carrera.objects.all()
    institutos = Instituto.objects.all()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        perfil_form = UsuarioForm(request.POST)
        if form.is_valid() and perfil_form.is_valid():
            user = form.save()
            perfil = perfil_form.save(commit=False)
            perfil.user = user
            perfil.save()
            login(request, user)
            return redirect('inicio')
    else: 
        form = UserCreationForm()
        perfil_form = UsuarioForm()
    
    return render(request, 'registration/registro.html', {'form': form, 'perfil_form': perfil_form, 'institutos': institutos, 'carreras': carreras})
    

@login_required
def tests(request, test_nombre):
    color_fondo = random.choice(COLORES)
    tests = Test.objects.get(nombre=test_nombre)
    preguntas = Pregunta.objects.filter(test=tests)

    if request.method == 'POST':
        respuestas = []
        for key, value in request.POST.items():
            if key.startswith('pregunta'):
                respuesta = {
                    'pregunta_id': key,
                    'opcion_id': value
                }
                respuestas.append(respuesta)

        for respuesta in respuestas:
            pregunta_id = respuesta['pregunta_id'].replace('pregunta', '')
            opcion_id = respuesta['opcion_id']

            pregunta = Pregunta.objects.get(pk=pregunta_id)
            opcion = OpcionRespuesta.objects.get(pk=opcion_id)

            nueva_respuesta = Respuesta(
                user=request.user,
                test=tests,
                pregunta=pregunta,
                opcion_respuesta=opcion
            )
            nueva_respuesta.save()
        return redirect('inicio')
        

    return render(request, 'tests.html', {'preguntas': preguntas, 'color_fondo': color_fondo, 'test_nombre': test_nombre})

@login_required
def salir(request):
    logout(request)
    return redirect('/')

libreria/templates/afectacionAcademica.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&family=Roboto:wght@100;400;700;900&display=swap"
            rel="stylesheet">
        <link
            rel="shortcut icon"
            href="https://cdn-icons-png.flaticon.com/512/3923/3923306.png" />
            <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="{% static 'css/normalize.css' %}" rel="stylesheet" />
        <link href="{% static 'css/index.css' %}" rel="stylesheet" />
        <title>Test EDDS</title>
    </head>
    <body style="background-color: #d9efde;">
        <div>
            <header class="header-preguntas" style="background-color: #009634;"></header>

            <div class="contenedor-preguntas"> <!-- solo pone margin-->
                <div class="contenedor contenido-preguntas">
                    <!-- centra el contenido y le da un display flex-->
                    <form action="#" method="POST">
                        <div class="pregunta">
                            <h1 class="titulo-pregunta">Test Afeccion academica</h1>
                        </div>

                        {% for pregunta in preguntas %}
                        <div class="pregunta">
                            <label>{{ pregunta.pregunta }}</label>
                            {% for opcion in pregunta.opcionrespuesta_set.all %}
                            <div>
                                <input id="{{ opcion.id }}" type="radio"
                                    name="pregunta{{ pregunta.id }}"
                                    value="{{ opcion.id }}">
                                <label for="{{ opcion.id }}">{{ opcion.opcion }}</label>
                            </div>
                            {% endfor %}
                        </div>
                        {% endfor %}

                        <input type="submit" value="Enviar">
                        {% csrf_token %}
                    </form>

                </div>
            </div>
        </div>

        <a class="ayuda" href="http://www.google.com">
            <i class="fa-regular fa-question fa-beat"></i>
        </a>

        <footer class="footer">
            <p><span>Test</span> TecNM</p>
        </footer>
    </body>
</html>

libreria/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&family=Roboto:wght@100;400;700;900&display=swap"
            rel="stylesheet">
        <link
            rel="shortcut icon"
            href="https://cdn-icons-png.flaticon.com/512/3923/3923306.png" />
        <link href="{% static 'css/normalize.css' %}" rel="stylesheet" />
        <link href="{% static 'css/index.css' %}" rel="stylesheet" />

        <title>Inicio</title>
    </head>
    <body>
        <header class="header">
            <div class="contenedor imagen-header">
                <picture>
                    <source
                        sizes="1920w"
                        srcset="{% static 'img/logotec.avif' %} 1920w"
                        type="image/avif">
                    <source
                        sizes="1920w"
                        srcset="{% static 'img/logotec.webp' %} 1920w"
                        type="image/webp">
                    <source
                        sizes="1920w"
                        srcset="{% static 'img/logotec.png' %} 1920w"
                        type="image/jpeg">
                    <img loading="lazy" decoding="async"
                        src="{% static 'img/logotec.png' %}"
                        lazyalt="imagen" width="500" height="300">
                </picture>

                <p>TestTecNM</p>
            </div>

            <a href="{% url 'salir' %}">Cerrar sesion</a>
        </header>

        <main class="main-test">
            <div class="contenedor">
                <p>Inicia un test</p>
                <div class="contenedor-test">
                    <div>
                        <div>
                            <a href="{% url 'depresion' %}">
                                <div class="test">
                                    <img
                                        src="https://cdn.discordapp.com/attachments/1060055781493461002/1117664968607813682/image.png"
                                        alt>
                                </div>
                            </a>
                            <p>Test depresión</p>
                        </div>
                    </div>
                    <div>
                        <a href="{% url 'mdq' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/1rchdLXfwxXLQh2TI1-tZd-I4tNvlbODgIv6GH-QpZ9w_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test de desorden emocional</p>
                    </div>
                    <div>
                        <a href="{% url 'alcoholismo' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/1R2sTjfMFHee6VYVhuz8Tpi78mROlLWY4XgaKkJKMuis_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test alcoholismo</p>
                    </div>
                    <div>
                        <a href="{% url 'drogas' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/1SBlHGgVWqRrNBBVIt0oDwKXYURgH1-5r0LpxlI-kATQ_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test consumo de drogas</p>
                    </div>

                    <div>
                        <a href="{% url 'beck' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/1SBlHGgVWqRrNBBVIt0oDwKXYURgH1-5r0LpxlI-kATQ_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test desesperanza</p>
                    </div>
                    <div>
                        <a href="{% url 'edds' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/11WVGXvIGFPpigMHbb6zO5Xti-Hzl2GUECtvrphTqwhE_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test de desorden alimenticio</p>
                    </div>

                    <div>
                        <a href="{% url 'ansiedad' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/11WVGXvIGFPpigMHbb6zO5Xti-Hzl2GUECtvrphTqwhE_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test de ansiedad</p>
                    </div>

                    <div>
                        <a href="{% url 'estres' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/11WVGXvIGFPpigMHbb6zO5Xti-Hzl2GUECtvrphTqwhE_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Test de estres</p>
                    </div>

                    <div>
                        <a href="{% url 'afecciónAcadémica' %}">
                            <div class="test">
                                <img
                                    src="https://ssl.gstatic.com/docs/templates/thumbnails/11WVGXvIGFPpigMHbb6zO5Xti-Hzl2GUECtvrphTqwhE_400.png"
                                    alt>
                            </div>
                        </a>
                        <p>Afectacion Academica</p>
                    </div>

                </div>
            </div>
        </main>

        <section class="realizados">
            <div class="contenedor ">
                <p>Test realizados</p>
                <div class="contenedor-test-realizados ">

                    <div class="test-realizados">
                        <img
                            src="https://lh3.googleusercontent.com/fife/APg5EOZtoWXup3j4swh4cXBPqCzCT4pg7Wf9cF7RmBiz7VbGlcwnPkDxXzA_SQxLtg_O0CwBW4O7NXGD8iPDBCATb5phneZZ48oc922juRO7q3Lp1SLa5EhyFWIdTepM_3DFig_quz0uiobcYDsnNpqE3yAwHTCMe06ee1PQvtm6c5qvICy0OIh2H7e31th7hCTKa-jyNr0kO8TqRmEJkkhFVQZ_z2LzfQjR1-OD7q2ZRKt_Fi0pQuyGQcDlM90vSsBpH_nVliYIqLvknCNlSWqfWmC7qKZJDrX5U62A735uxPC7GxmRJsAGEaHQZW27VfjmIhnrLrzt5SYEMBgJdJl7s0_0D0jJKqZtL_ZO1nvyBpVp4_Hez59o3pWxmJ-GZGM_O6xrBCISq4NSoOJnD4UecU8QENcCuAMA38lOOKTw3P-fwFG_akXRPtp0F78e_VnneUviBKZO5Xdc3_UtPan-0Ed-3CdKAIkwiCmeAJyKuX5slaJZ_Zl2xyfjzltcPbffNP6X00Js5fTHSFypzGV17NS5SM7YsLs4WKnHYjSZAWGaKV8CccjbZ34hxa9YrVmgDbfZ3obnXz2HSW2FxGi-OyfRaBvlwAU6SDrS1SRDeQyrZZjpZFF2f20JujYA3TyaqRAVogOTNsXQrSEogYSwet-RLroeuDiojnjnWWpIPeWdthCXm15FQok9n8Fks6WDvS-2-pnXxSPlYEU0ThM5NGFeu24qyKuBGE1dLEajseEfW8ACTw5f4QvHhANOKWZeQ7BF_Ni0KFaWNyRVb4o2yEhW1EttE4GVsX3Trut-6Ul2FEjRmWkZUXtmBXin9ddXHBOJjM6LpIZ71VafXN6gWxOh_r-CvxDz-1ade7PstjeErFnIsABnNFRgA6IFxrf4N-EX-13wyp9YxFIsDC4FBpygVpddp2XR4dyYYbN29dcfA22XUFmD_LFBnsaClctxsR7j9WFY7sbu0Lg5SZG4PVyjLKOt94BzmdMFhqBvshfg53OkSK9p4WP2GZfsl1MCl_IEhpkKd364fE_98A3R6T61CzFCm96Ixsy6JniMeuMxNxRzEpXmPCjajboYDoEw4fqv5rzUznDmrs2rSp59G7e51vgmI_zTy60-lAK-HBkpEVmuLaSVEAK6fObIN4vKtIOqM02mDNQgxPZUjsiBm6SZZSPJPv3RHyUoJRb6XGVHOpEPM1hyXuO0zbDAwxmcDKOZPPssl2DpA23YkIPFh6GfdJIbUUGgPju8GtunS42oSVEOm4-1e6xRw7-9wf6kFtbfPQ6ynNzuKEo5xDczCMLrq12Pz_Tdoa7-V76J6NlfhQnqiyFU0nUMCGDXSGrvThq9Bt8kyKyMLFvIyCeSsJNhva_rcPuqtT9WmX1gziHS7X0wVNZ_52EbY71hEhIpEpxJbzuKwLJepnVwMK7J7XqPrf7HQtsufjMAlfvjdOyijUsFSWIiMj7_ssXmYakhYmZXbTVqtuNLjSLBh2khsURdM7Hut21X6bQnFkPr49NPufGPtkIY4_C1G-ainpo5oF-4g_Jv4jE2mfSf_kwDxp0OuZ8xyzgKlNmq6Zeyv-nwO1zjRf8aeYvf0KK1dwK55lzxsrIXGqoR3bfzlnZ6J60Y3zz-rfq6vfbxtdBES3FBYO6CKDD_01hEIgTccH6C=w416-h312-p"
                            alt>
                        <div class="texto-test">
                            <p>Test ansiedad</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </body>
</html>

libreria/templates/tests.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&family=Roboto:wght@100;400;700;900&display=swap"
            rel="stylesheet">
        <link
            rel="shortcut icon"
            href="https://cdn-icons-png.flaticon.com/512/3923/3923306.png" />
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="{% static 'css/normalize.css' %}" rel="stylesheet" />
        <link href="{% static 'css/index.css' %}" rel="stylesheet" />
        <title>{{ test_nombre }}</title>

    </head>
    <body style="background-color: {{ color_fondo }};">
        <div>
            <header class="header-preguntas"
                style="background-color: {{ color_fondo }};"></header>

            <div class="contenedor-preguntas"> <!-- solo pone margin-->
                <div class="contenedor contenido-preguntas">
                    <!-- centra el contenido y le da un display flex-->
                    <form id="test-form" action method="POST">
                        <div class="pregunta">
                            <h1 class="titulo-pregunta">Test de {{test_nombre}}</h1>
                        </div>

                        {% for pregunta in preguntas %}
                        <div class="pregunta test-validar">
                            <label>{{ pregunta.pregunta }}</label>
                            {% for opcion in pregunta.opcionrespuesta_set.all %}
                            <div>
                                <input id="{{ opcion.id }}" type="radio"
                                    name="pregunta{{ pregunta.id }}"
                                    value="{{ opcion.id }}">
                                <label for="{{ opcion.id }}">{{ opcion.opcion }}</label>
                            </div>
                            {% endfor %}
                        </div>
                        {% endfor %}

                        <input type="submit" value="Enviar">
                        {% csrf_token %}
                    </form>

                </div>
            </div>
        </div>

        <footer class="footer">
            <p><span>Test</span> TecNM</p>
        </footer>

        <script src="{% static 'js/validarTests.js' %}"></script>
    </body>
</html>